/*
 * AMSVR Broker API
 *
 * # Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##        
 *
 * API version: release-0.6.0.24
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package broker
// AfsluitingZaakStatusEnum the model 'AfsluitingZaakStatusEnum'
type AfsluitingZaakStatusEnum string

// List of AfsluitingZaakStatusEnum
const (
	AFSLUITINGZAAKSTATUSENUM_NIEUW AfsluitingZaakStatusEnum = "nieuw"
	AFSLUITINGZAAKSTATUSENUM_INGEDIEND AfsluitingZaakStatusEnum = "ingediend"
	AFSLUITINGZAAKSTATUSENUM_AFGEWEZEN AfsluitingZaakStatusEnum = "afgewezen"
	AFSLUITINGZAAKSTATUSENUM_GOEDGEKEURD AfsluitingZaakStatusEnum = "goedgekeurd"
	AFSLUITINGZAAKSTATUSENUM_BEVESTIGD AfsluitingZaakStatusEnum = "bevestigd"
	AFSLUITINGZAAKSTATUSENUM_UITGEVOERD AfsluitingZaakStatusEnum = "uitgevoerd"
	AFSLUITINGZAAKSTATUSENUM_GEANNULEERD AfsluitingZaakStatusEnum = "geannuleerd"
)
