/*
AMSVR Broker API

# Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##        

API version: release-0.6.14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package broker

import (
	"encoding/json"
)

// Criterium struct for Criterium
type Criterium struct {
	Id int32 `json:"id"`
	Naam int32 `json:"naam"`
	Description NullableString `json:"description,omitempty"`
}

// NewCriterium instantiates a new Criterium object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCriterium(id int32, naam int32) *Criterium {
	this := Criterium{}
	this.Id = id
	this.Naam = naam
	return &this
}

// NewCriteriumWithDefaults instantiates a new Criterium object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCriteriumWithDefaults() *Criterium {
	this := Criterium{}
	return &this
}

// GetId returns the Id field value
func (o *Criterium) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Criterium) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Criterium) SetId(v int32) {
	o.Id = v
}

// GetNaam returns the Naam field value
func (o *Criterium) GetNaam() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Naam
}

// GetNaamOk returns a tuple with the Naam field value
// and a boolean to check if the value has been set.
func (o *Criterium) GetNaamOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Naam, true
}

// SetNaam sets field value
func (o *Criterium) SetNaam(v int32) {
	o.Naam = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Criterium) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Criterium) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *Criterium) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *Criterium) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *Criterium) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *Criterium) UnsetDescription() {
	o.Description.Unset()
}

func (o Criterium) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["naam"] = o.Naam
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableCriterium struct {
	value *Criterium
	isSet bool
}

func (v NullableCriterium) Get() *Criterium {
	return v.value
}

func (v *NullableCriterium) Set(val *Criterium) {
	v.value = val
	v.isSet = true
}

func (v NullableCriterium) IsSet() bool {
	return v.isSet
}

func (v *NullableCriterium) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCriterium(val *Criterium) *NullableCriterium {
	return &NullableCriterium{value: val, isSet: true}
}

func (v NullableCriterium) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCriterium) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


