/*
AMSVR Broker API

# Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##        

API version: release-0.6.14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package broker

import (
	"encoding/json"
)

// AanwezigCriteriumRequest struct for AanwezigCriteriumRequest
type AanwezigCriteriumRequest struct {
	Criterium int32 `json:"criterium"`
}

// NewAanwezigCriteriumRequest instantiates a new AanwezigCriteriumRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAanwezigCriteriumRequest(criterium int32) *AanwezigCriteriumRequest {
	this := AanwezigCriteriumRequest{}
	this.Criterium = criterium
	return &this
}

// NewAanwezigCriteriumRequestWithDefaults instantiates a new AanwezigCriteriumRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAanwezigCriteriumRequestWithDefaults() *AanwezigCriteriumRequest {
	this := AanwezigCriteriumRequest{}
	return &this
}

// GetCriterium returns the Criterium field value
func (o *AanwezigCriteriumRequest) GetCriterium() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Criterium
}

// GetCriteriumOk returns a tuple with the Criterium field value
// and a boolean to check if the value has been set.
func (o *AanwezigCriteriumRequest) GetCriteriumOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Criterium, true
}

// SetCriterium sets field value
func (o *AanwezigCriteriumRequest) SetCriterium(v int32) {
	o.Criterium = v
}

func (o AanwezigCriteriumRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["criterium"] = o.Criterium
	}
	return json.Marshal(toSerialize)
}

type NullableAanwezigCriteriumRequest struct {
	value *AanwezigCriteriumRequest
	isSet bool
}

func (v NullableAanwezigCriteriumRequest) Get() *AanwezigCriteriumRequest {
	return v.value
}

func (v *NullableAanwezigCriteriumRequest) Set(val *AanwezigCriteriumRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAanwezigCriteriumRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAanwezigCriteriumRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAanwezigCriteriumRequest(val *AanwezigCriteriumRequest) *NullableAanwezigCriteriumRequest {
	return &NullableAanwezigCriteriumRequest{value: val, isSet: true}
}

func (v NullableAanwezigCriteriumRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAanwezigCriteriumRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


