/*
AMSVR Broker API

# Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##        

API version: release-0.6.14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package broker

import (
	"encoding/json"
)

// PatchedSectorToestandRequest struct for PatchedSectorToestandRequest
type PatchedSectorToestandRequest struct {
	// 0 = Test, 1 = Actief, 2 = Passief
	Toestand NullableMeldingToestand `json:"toestand,omitempty"`
}

// NewPatchedSectorToestandRequest instantiates a new PatchedSectorToestandRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedSectorToestandRequest() *PatchedSectorToestandRequest {
	this := PatchedSectorToestandRequest{}
	return &this
}

// NewPatchedSectorToestandRequestWithDefaults instantiates a new PatchedSectorToestandRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedSectorToestandRequestWithDefaults() *PatchedSectorToestandRequest {
	this := PatchedSectorToestandRequest{}
	return &this
}

// GetToestand returns the Toestand field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedSectorToestandRequest) GetToestand() MeldingToestand {
	if o == nil || o.Toestand.Get() == nil {
		var ret MeldingToestand
		return ret
	}
	return *o.Toestand.Get()
}

// GetToestandOk returns a tuple with the Toestand field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedSectorToestandRequest) GetToestandOk() (*MeldingToestand, bool) {
	if o == nil {
		return nil, false
	}
	return o.Toestand.Get(), o.Toestand.IsSet()
}

// HasToestand returns a boolean if a field has been set.
func (o *PatchedSectorToestandRequest) HasToestand() bool {
	if o != nil && o.Toestand.IsSet() {
		return true
	}

	return false
}

// SetToestand gets a reference to the given NullableMeldingToestand and assigns it to the Toestand field.
func (o *PatchedSectorToestandRequest) SetToestand(v MeldingToestand) {
	o.Toestand.Set(&v)
}
// SetToestandNil sets the value for Toestand to be an explicit nil
func (o *PatchedSectorToestandRequest) SetToestandNil() {
	o.Toestand.Set(nil)
}

// UnsetToestand ensures that no value is present for Toestand, not even an explicit nil
func (o *PatchedSectorToestandRequest) UnsetToestand() {
	o.Toestand.Unset()
}

func (o PatchedSectorToestandRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Toestand.IsSet() {
		toSerialize["toestand"] = o.Toestand.Get()
	}
	return json.Marshal(toSerialize)
}

type NullablePatchedSectorToestandRequest struct {
	value *PatchedSectorToestandRequest
	isSet bool
}

func (v NullablePatchedSectorToestandRequest) Get() *PatchedSectorToestandRequest {
	return v.value
}

func (v *NullablePatchedSectorToestandRequest) Set(val *PatchedSectorToestandRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedSectorToestandRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedSectorToestandRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedSectorToestandRequest(val *PatchedSectorToestandRequest) *NullablePatchedSectorToestandRequest {
	return &NullablePatchedSectorToestandRequest{value: val, isSet: true}
}

func (v NullablePatchedSectorToestandRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedSectorToestandRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


