/*
 * AMSVR Broker API
 *
 * # Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##        
 *
 * API version: release-0.6.0.24
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package broker
// AansluitingStatusEnum the model 'AansluitingStatusEnum'
type AansluitingStatusEnum int32

// List of AansluitingStatusEnum
const (
	AANSLUITINGSTATUSENUM__0 AansluitingStatusEnum = 0
	AANSLUITINGSTATUSENUM__10 AansluitingStatusEnum = 10
	AANSLUITINGSTATUSENUM__20 AansluitingStatusEnum = 20
	AANSLUITINGSTATUSENUM__30 AansluitingStatusEnum = 30
	AANSLUITINGSTATUSENUM__50 AansluitingStatusEnum = 50
	AANSLUITINGSTATUSENUM__55 AansluitingStatusEnum = 55
	AANSLUITINGSTATUSENUM__60 AansluitingStatusEnum = 60
	AANSLUITINGSTATUSENUM__5 AansluitingStatusEnum = 5
	AANSLUITINGSTATUSENUM__61 AansluitingStatusEnum = 61
)
