/*
AMSVR Broker API

# Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##        

API version: release-0.6.14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package broker

import (
	"encoding/json"
)

// PatchedContactPersoonRequest struct for PatchedContactPersoonRequest
type PatchedContactPersoonRequest struct {
	Voornaam NullableString `json:"voornaam,omitempty"`
	Tussenvoegsel NullableString `json:"tussenvoegsel,omitempty"`
	Achternaam *string `json:"achternaam,omitempty"`
	IsTechnischContact *bool `json:"is_technisch_contact,omitempty"`
	// contactpersoon t.b.v. informatie voor de repressieve dienst (verplicht voor een technisch contact)
	Email NullableString `json:"email,omitempty"`
}

// NewPatchedContactPersoonRequest instantiates a new PatchedContactPersoonRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedContactPersoonRequest() *PatchedContactPersoonRequest {
	this := PatchedContactPersoonRequest{}
	return &this
}

// NewPatchedContactPersoonRequestWithDefaults instantiates a new PatchedContactPersoonRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedContactPersoonRequestWithDefaults() *PatchedContactPersoonRequest {
	this := PatchedContactPersoonRequest{}
	return &this
}

// GetVoornaam returns the Voornaam field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedContactPersoonRequest) GetVoornaam() string {
	if o == nil || o.Voornaam.Get() == nil {
		var ret string
		return ret
	}
	return *o.Voornaam.Get()
}

// GetVoornaamOk returns a tuple with the Voornaam field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedContactPersoonRequest) GetVoornaamOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Voornaam.Get(), o.Voornaam.IsSet()
}

// HasVoornaam returns a boolean if a field has been set.
func (o *PatchedContactPersoonRequest) HasVoornaam() bool {
	if o != nil && o.Voornaam.IsSet() {
		return true
	}

	return false
}

// SetVoornaam gets a reference to the given NullableString and assigns it to the Voornaam field.
func (o *PatchedContactPersoonRequest) SetVoornaam(v string) {
	o.Voornaam.Set(&v)
}
// SetVoornaamNil sets the value for Voornaam to be an explicit nil
func (o *PatchedContactPersoonRequest) SetVoornaamNil() {
	o.Voornaam.Set(nil)
}

// UnsetVoornaam ensures that no value is present for Voornaam, not even an explicit nil
func (o *PatchedContactPersoonRequest) UnsetVoornaam() {
	o.Voornaam.Unset()
}

// GetTussenvoegsel returns the Tussenvoegsel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedContactPersoonRequest) GetTussenvoegsel() string {
	if o == nil || o.Tussenvoegsel.Get() == nil {
		var ret string
		return ret
	}
	return *o.Tussenvoegsel.Get()
}

// GetTussenvoegselOk returns a tuple with the Tussenvoegsel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedContactPersoonRequest) GetTussenvoegselOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tussenvoegsel.Get(), o.Tussenvoegsel.IsSet()
}

// HasTussenvoegsel returns a boolean if a field has been set.
func (o *PatchedContactPersoonRequest) HasTussenvoegsel() bool {
	if o != nil && o.Tussenvoegsel.IsSet() {
		return true
	}

	return false
}

// SetTussenvoegsel gets a reference to the given NullableString and assigns it to the Tussenvoegsel field.
func (o *PatchedContactPersoonRequest) SetTussenvoegsel(v string) {
	o.Tussenvoegsel.Set(&v)
}
// SetTussenvoegselNil sets the value for Tussenvoegsel to be an explicit nil
func (o *PatchedContactPersoonRequest) SetTussenvoegselNil() {
	o.Tussenvoegsel.Set(nil)
}

// UnsetTussenvoegsel ensures that no value is present for Tussenvoegsel, not even an explicit nil
func (o *PatchedContactPersoonRequest) UnsetTussenvoegsel() {
	o.Tussenvoegsel.Unset()
}

// GetAchternaam returns the Achternaam field value if set, zero value otherwise.
func (o *PatchedContactPersoonRequest) GetAchternaam() string {
	if o == nil || o.Achternaam == nil {
		var ret string
		return ret
	}
	return *o.Achternaam
}

// GetAchternaamOk returns a tuple with the Achternaam field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedContactPersoonRequest) GetAchternaamOk() (*string, bool) {
	if o == nil || o.Achternaam == nil {
		return nil, false
	}
	return o.Achternaam, true
}

// HasAchternaam returns a boolean if a field has been set.
func (o *PatchedContactPersoonRequest) HasAchternaam() bool {
	if o != nil && o.Achternaam != nil {
		return true
	}

	return false
}

// SetAchternaam gets a reference to the given string and assigns it to the Achternaam field.
func (o *PatchedContactPersoonRequest) SetAchternaam(v string) {
	o.Achternaam = &v
}

// GetIsTechnischContact returns the IsTechnischContact field value if set, zero value otherwise.
func (o *PatchedContactPersoonRequest) GetIsTechnischContact() bool {
	if o == nil || o.IsTechnischContact == nil {
		var ret bool
		return ret
	}
	return *o.IsTechnischContact
}

// GetIsTechnischContactOk returns a tuple with the IsTechnischContact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedContactPersoonRequest) GetIsTechnischContactOk() (*bool, bool) {
	if o == nil || o.IsTechnischContact == nil {
		return nil, false
	}
	return o.IsTechnischContact, true
}

// HasIsTechnischContact returns a boolean if a field has been set.
func (o *PatchedContactPersoonRequest) HasIsTechnischContact() bool {
	if o != nil && o.IsTechnischContact != nil {
		return true
	}

	return false
}

// SetIsTechnischContact gets a reference to the given bool and assigns it to the IsTechnischContact field.
func (o *PatchedContactPersoonRequest) SetIsTechnischContact(v bool) {
	o.IsTechnischContact = &v
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedContactPersoonRequest) GetEmail() string {
	if o == nil || o.Email.Get() == nil {
		var ret string
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedContactPersoonRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *PatchedContactPersoonRequest) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableString and assigns it to the Email field.
func (o *PatchedContactPersoonRequest) SetEmail(v string) {
	o.Email.Set(&v)
}
// SetEmailNil sets the value for Email to be an explicit nil
func (o *PatchedContactPersoonRequest) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *PatchedContactPersoonRequest) UnsetEmail() {
	o.Email.Unset()
}

func (o PatchedContactPersoonRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Voornaam.IsSet() {
		toSerialize["voornaam"] = o.Voornaam.Get()
	}
	if o.Tussenvoegsel.IsSet() {
		toSerialize["tussenvoegsel"] = o.Tussenvoegsel.Get()
	}
	if o.Achternaam != nil {
		toSerialize["achternaam"] = o.Achternaam
	}
	if o.IsTechnischContact != nil {
		toSerialize["is_technisch_contact"] = o.IsTechnischContact
	}
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	return json.Marshal(toSerialize)
}

type NullablePatchedContactPersoonRequest struct {
	value *PatchedContactPersoonRequest
	isSet bool
}

func (v NullablePatchedContactPersoonRequest) Get() *PatchedContactPersoonRequest {
	return v.value
}

func (v *NullablePatchedContactPersoonRequest) Set(val *PatchedContactPersoonRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedContactPersoonRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedContactPersoonRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedContactPersoonRequest(val *PatchedContactPersoonRequest) *NullablePatchedContactPersoonRequest {
	return &NullablePatchedContactPersoonRequest{value: val, isSet: true}
}

func (v NullablePatchedContactPersoonRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedContactPersoonRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


