/*
 * AMSVR Broker API
 *
 * # Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##        
 *
 * API version: release-0.6.0.24
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package broker
import (
	"time"
)
// Waarschuwingsadres struct for Waarschuwingsadres
type Waarschuwingsadres struct {
	Id int32 `json:"id"`
	Telefoonnummer int32 `json:"telefoonnummer"`
	// De contactpersoon met de hoogste prioriteit wordt als eerste opgeroepen
	Prioriteit int32 `json:"prioriteit,omitempty"`
	Created time.Time `json:"created"`
	Modified time.Time `json:"modified"`
}
