/*
AMSVR Broker API

# Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##

API version: release-0.6.14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package broker

import (
	"encoding/json"
)

// PatchedAansluitingBestandRequest struct for PatchedAansluitingBestandRequest
type PatchedAansluitingBestandRequest struct {
	Naam         *string        `json:"naam,omitempty"`
	Omschrijving NullableString `json:"omschrijving,omitempty"`
	// overige = Overige, pve = PVE, upd = UPD, nva = NVA (nota van aanvulling), nvw = NVW (nota van wijzigingen), gms_mutatierapport = GMS mutatierapport
	Type NullableAansluitingBestandTypeEnum `json:"type,omitempty"`
	File NullableString                     `json:"file,omitempty"`
}

// NewPatchedAansluitingBestandRequest instantiates a new PatchedAansluitingBestandRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedAansluitingBestandRequest() *PatchedAansluitingBestandRequest {
	this := PatchedAansluitingBestandRequest{}
	return &this
}

// NewPatchedAansluitingBestandRequestWithDefaults instantiates a new PatchedAansluitingBestandRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedAansluitingBestandRequestWithDefaults() *PatchedAansluitingBestandRequest {
	this := PatchedAansluitingBestandRequest{}
	return &this
}

// GetNaam returns the Naam field value if set, zero value otherwise.
func (o *PatchedAansluitingBestandRequest) GetNaam() string {
	if o == nil || o.Naam == nil {
		var ret string
		return ret
	}
	return *o.Naam
}

// GetNaamOk returns a tuple with the Naam field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedAansluitingBestandRequest) GetNaamOk() (*string, bool) {
	if o == nil || o.Naam == nil {
		return nil, false
	}
	return o.Naam, true
}

// HasNaam returns a boolean if a field has been set.
func (o *PatchedAansluitingBestandRequest) HasNaam() bool {
	if o != nil && o.Naam != nil {
		return true
	}

	return false
}

// SetNaam gets a reference to the given string and assigns it to the Naam field.
func (o *PatchedAansluitingBestandRequest) SetNaam(v string) {
	o.Naam = &v
}

// GetOmschrijving returns the Omschrijving field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedAansluitingBestandRequest) GetOmschrijving() string {
	if o == nil || o.Omschrijving.Get() == nil {
		var ret string
		return ret
	}
	return *o.Omschrijving.Get()
}

// GetOmschrijvingOk returns a tuple with the Omschrijving field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedAansluitingBestandRequest) GetOmschrijvingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Omschrijving.Get(), o.Omschrijving.IsSet()
}

// HasOmschrijving returns a boolean if a field has been set.
func (o *PatchedAansluitingBestandRequest) HasOmschrijving() bool {
	if o != nil && o.Omschrijving.IsSet() {
		return true
	}

	return false
}

// SetOmschrijving gets a reference to the given NullableString and assigns it to the Omschrijving field.
func (o *PatchedAansluitingBestandRequest) SetOmschrijving(v string) {
	o.Omschrijving.Set(&v)
}

// SetOmschrijvingNil sets the value for Omschrijving to be an explicit nil
func (o *PatchedAansluitingBestandRequest) SetOmschrijvingNil() {
	o.Omschrijving.Set(nil)
}

// UnsetOmschrijving ensures that no value is present for Omschrijving, not even an explicit nil
func (o *PatchedAansluitingBestandRequest) UnsetOmschrijving() {
	o.Omschrijving.Unset()
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedAansluitingBestandRequest) GetType() AansluitingBestandTypeEnum {
	if o == nil || o.Type.Get() == nil {
		var ret AansluitingBestandTypeEnum
		return ret
	}
	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedAansluitingBestandRequest) GetTypeOk() (*AansluitingBestandTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// HasType returns a boolean if a field has been set.
func (o *PatchedAansluitingBestandRequest) HasType() bool {
	if o != nil && o.Type.IsSet() {
		return true
	}

	return false
}

// SetType gets a reference to the given NullableAansluitingBestandTypeEnum and assigns it to the Type field.
func (o *PatchedAansluitingBestandRequest) SetType(v AansluitingBestandTypeEnum) {
	o.Type.Set(&v)
}

// SetTypeNil sets the value for Type to be an explicit nil
func (o *PatchedAansluitingBestandRequest) SetTypeNil() {
	o.Type.Set(nil)
}

// UnsetType ensures that no value is present for Type, not even an explicit nil
func (o *PatchedAansluitingBestandRequest) UnsetType() {
	o.Type.Unset()
}

// GetFile returns the File field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedAansluitingBestandRequest) GetFile() *string {
	if o == nil || o.File.Get() == nil {
		var ret *string
		return ret
	}
	return o.File.Get()
}

// GetFileOk returns a tuple with the File field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedAansluitingBestandRequest) GetFileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.File.Get(), o.File.IsSet()
}

// HasFile returns a boolean if a field has been set.
func (o *PatchedAansluitingBestandRequest) HasFile() bool {
	if o != nil && o.File.IsSet() {
		return true
	}

	return false
}

// SetFile gets a reference to the given Nullable*string and assigns it to the File field.
func (o *PatchedAansluitingBestandRequest) SetFile(v *string) {
	o.File.Set(v)
}

// SetFileNil sets the value for File to be an explicit nil
func (o *PatchedAansluitingBestandRequest) SetFileNil() {
	o.File.Set(nil)
}

// UnsetFile ensures that no value is present for File, not even an explicit nil
func (o *PatchedAansluitingBestandRequest) UnsetFile() {
	o.File.Unset()
}

func (o PatchedAansluitingBestandRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Naam != nil {
		toSerialize["naam"] = o.Naam
	}
	if o.Omschrijving.IsSet() {
		toSerialize["omschrijving"] = o.Omschrijving.Get()
	}
	if o.Type.IsSet() {
		toSerialize["type"] = o.Type.Get()
	}
	if o.File.IsSet() {
		toSerialize["file"] = o.File.Get()
	}
	return json.Marshal(toSerialize)
}

type NullablePatchedAansluitingBestandRequest struct {
	value *PatchedAansluitingBestandRequest
	isSet bool
}

func (v NullablePatchedAansluitingBestandRequest) Get() *PatchedAansluitingBestandRequest {
	return v.value
}

func (v *NullablePatchedAansluitingBestandRequest) Set(val *PatchedAansluitingBestandRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedAansluitingBestandRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedAansluitingBestandRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedAansluitingBestandRequest(val *PatchedAansluitingBestandRequest) *NullablePatchedAansluitingBestandRequest {
	return &NullablePatchedAansluitingBestandRequest{value: val, isSet: true}
}

func (v NullablePatchedAansluitingBestandRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedAansluitingBestandRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
