/*
AMSVR Broker API

# Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##        

API version: release-0.6.14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package broker

import (
	"encoding/json"
	"time"
)

// NieuweAansluitingZaak struct for NieuweAansluitingZaak
type NieuweAansluitingZaak struct {
	Id int32 `json:"id"`
	Aansluiting int32 `json:"aansluiting"`
	// nieuw = Nieuw, ingediend = Ingediend ter aanvraag [ATSP], afgekeurd = Aanvraag afgekeurd [Risicobeheer], realisatie = Aanvraag goedgekeurd [Risicobeheer], gms_doorgevoerd = Doorgevoerd [GMS], technisch_gereed = Live test ingepland [ATSP], goedgekeurd = Goedgekeurd [AMS-Servicedesk], opgeleverd = Actief gezet [Risicobeheer], geannuleerd = Geannuleerd
	Status NullableNieuweAansluitingZaakStatusEnum `json:"status"`
	StatusChanged time.Time `json:"status_changed"`
	Created time.Time `json:"created"`
	Modified time.Time `json:"modified"`
	User NullableInt32 `json:"user"`
	Gesloten bool `json:"gesloten"`
	GeslotenDoor NullableInt32 `json:"gesloten_door"`
	MogelijkeTransities []string `json:"mogelijke_transities"`
}

// NewNieuweAansluitingZaak instantiates a new NieuweAansluitingZaak object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNieuweAansluitingZaak(id int32, aansluiting int32, status NullableNieuweAansluitingZaakStatusEnum, statusChanged time.Time, created time.Time, modified time.Time, user NullableInt32, gesloten bool, geslotenDoor NullableInt32, mogelijkeTransities []string) *NieuweAansluitingZaak {
	this := NieuweAansluitingZaak{}
	this.Id = id
	this.Aansluiting = aansluiting
	this.Status = status
	this.StatusChanged = statusChanged
	this.Created = created
	this.Modified = modified
	this.User = user
	this.Gesloten = gesloten
	this.GeslotenDoor = geslotenDoor
	this.MogelijkeTransities = mogelijkeTransities
	return &this
}

// NewNieuweAansluitingZaakWithDefaults instantiates a new NieuweAansluitingZaak object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNieuweAansluitingZaakWithDefaults() *NieuweAansluitingZaak {
	this := NieuweAansluitingZaak{}
	return &this
}

// GetId returns the Id field value
func (o *NieuweAansluitingZaak) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *NieuweAansluitingZaak) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NieuweAansluitingZaak) SetId(v int32) {
	o.Id = v
}

// GetAansluiting returns the Aansluiting field value
func (o *NieuweAansluitingZaak) GetAansluiting() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Aansluiting
}

// GetAansluitingOk returns a tuple with the Aansluiting field value
// and a boolean to check if the value has been set.
func (o *NieuweAansluitingZaak) GetAansluitingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Aansluiting, true
}

// SetAansluiting sets field value
func (o *NieuweAansluitingZaak) SetAansluiting(v int32) {
	o.Aansluiting = v
}

// GetStatus returns the Status field value
// If the value is explicit nil, the zero value for NieuweAansluitingZaakStatusEnum will be returned
func (o *NieuweAansluitingZaak) GetStatus() NieuweAansluitingZaakStatusEnum {
	if o == nil || o.Status.Get() == nil {
		var ret NieuweAansluitingZaakStatusEnum
		return ret
	}

	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NieuweAansluitingZaak) GetStatusOk() (*NieuweAansluitingZaakStatusEnum, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// SetStatus sets field value
func (o *NieuweAansluitingZaak) SetStatus(v NieuweAansluitingZaakStatusEnum) {
	o.Status.Set(&v)
}

// GetStatusChanged returns the StatusChanged field value
func (o *NieuweAansluitingZaak) GetStatusChanged() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StatusChanged
}

// GetStatusChangedOk returns a tuple with the StatusChanged field value
// and a boolean to check if the value has been set.
func (o *NieuweAansluitingZaak) GetStatusChangedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusChanged, true
}

// SetStatusChanged sets field value
func (o *NieuweAansluitingZaak) SetStatusChanged(v time.Time) {
	o.StatusChanged = v
}

// GetCreated returns the Created field value
func (o *NieuweAansluitingZaak) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *NieuweAansluitingZaak) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *NieuweAansluitingZaak) SetCreated(v time.Time) {
	o.Created = v
}

// GetModified returns the Modified field value
func (o *NieuweAansluitingZaak) GetModified() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value
// and a boolean to check if the value has been set.
func (o *NieuweAansluitingZaak) GetModifiedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Modified, true
}

// SetModified sets field value
func (o *NieuweAansluitingZaak) SetModified(v time.Time) {
	o.Modified = v
}

// GetUser returns the User field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *NieuweAansluitingZaak) GetUser() int32 {
	if o == nil || o.User.Get() == nil {
		var ret int32
		return ret
	}

	return *o.User.Get()
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NieuweAansluitingZaak) GetUserOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.User.Get(), o.User.IsSet()
}

// SetUser sets field value
func (o *NieuweAansluitingZaak) SetUser(v int32) {
	o.User.Set(&v)
}

// GetGesloten returns the Gesloten field value
func (o *NieuweAansluitingZaak) GetGesloten() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Gesloten
}

// GetGeslotenOk returns a tuple with the Gesloten field value
// and a boolean to check if the value has been set.
func (o *NieuweAansluitingZaak) GetGeslotenOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gesloten, true
}

// SetGesloten sets field value
func (o *NieuweAansluitingZaak) SetGesloten(v bool) {
	o.Gesloten = v
}

// GetGeslotenDoor returns the GeslotenDoor field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *NieuweAansluitingZaak) GetGeslotenDoor() int32 {
	if o == nil || o.GeslotenDoor.Get() == nil {
		var ret int32
		return ret
	}

	return *o.GeslotenDoor.Get()
}

// GetGeslotenDoorOk returns a tuple with the GeslotenDoor field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NieuweAansluitingZaak) GetGeslotenDoorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.GeslotenDoor.Get(), o.GeslotenDoor.IsSet()
}

// SetGeslotenDoor sets field value
func (o *NieuweAansluitingZaak) SetGeslotenDoor(v int32) {
	o.GeslotenDoor.Set(&v)
}

// GetMogelijkeTransities returns the MogelijkeTransities field value
func (o *NieuweAansluitingZaak) GetMogelijkeTransities() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.MogelijkeTransities
}

// GetMogelijkeTransitiesOk returns a tuple with the MogelijkeTransities field value
// and a boolean to check if the value has been set.
func (o *NieuweAansluitingZaak) GetMogelijkeTransitiesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MogelijkeTransities, true
}

// SetMogelijkeTransities sets field value
func (o *NieuweAansluitingZaak) SetMogelijkeTransities(v []string) {
	o.MogelijkeTransities = v
}

func (o NieuweAansluitingZaak) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["aansluiting"] = o.Aansluiting
	}
	if true {
		toSerialize["status"] = o.Status.Get()
	}
	if true {
		toSerialize["status_changed"] = o.StatusChanged
	}
	if true {
		toSerialize["created"] = o.Created
	}
	if true {
		toSerialize["modified"] = o.Modified
	}
	if true {
		toSerialize["user"] = o.User.Get()
	}
	if true {
		toSerialize["gesloten"] = o.Gesloten
	}
	if true {
		toSerialize["gesloten_door"] = o.GeslotenDoor.Get()
	}
	if true {
		toSerialize["mogelijke_transities"] = o.MogelijkeTransities
	}
	return json.Marshal(toSerialize)
}

type NullableNieuweAansluitingZaak struct {
	value *NieuweAansluitingZaak
	isSet bool
}

func (v NullableNieuweAansluitingZaak) Get() *NieuweAansluitingZaak {
	return v.value
}

func (v *NullableNieuweAansluitingZaak) Set(val *NieuweAansluitingZaak) {
	v.value = val
	v.isSet = true
}

func (v NullableNieuweAansluitingZaak) IsSet() bool {
	return v.isSet
}

func (v *NullableNieuweAansluitingZaak) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNieuweAansluitingZaak(val *NieuweAansluitingZaak) *NullableNieuweAansluitingZaak {
	return &NullableNieuweAansluitingZaak{value: val, isSet: true}
}

func (v NullableNieuweAansluitingZaak) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNieuweAansluitingZaak) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


