/*
 * AMSVR Broker API
 *
 * # Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##        
 *
 * API version: release-0.6.0.24
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package broker
import (
	"os"
)
// PatchedAansluitingBestandRequest struct for PatchedAansluitingBestandRequest
type PatchedAansluitingBestandRequest struct {
	Naam string `json:"naam,omitempty"`
	Omschrijving *string `json:"omschrijving,omitempty"`
	// overige = Overige, pve = PVE, upd = UPD, nva = NVA (nota van aanvulling), nvw = NVW (nota van wijzigingen), gms_mutatierapport = GMS mutatierapport
	Type AansluitingBestandTypeEnum `json:"type,omitempty"`
	File **os.File `json:"file,omitempty"`
}
