/*
AMSVR Broker API

# Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##        

API version: release-0.6.14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package broker

import (
	"encoding/json"
	"fmt"
)

// MeldingStatus the model 'MeldingStatus'
type MeldingStatus int32

// List of MeldingStatus
const (
	MELDINGSTATUS__0 MeldingStatus = 0
	MELDINGSTATUS__1 MeldingStatus = 1
)

// All allowed values of MeldingStatus enum
var AllowedMeldingStatusEnumValues = []MeldingStatus{
	0,
	1,
}

func (v *MeldingStatus) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := MeldingStatus(value)
	for _, existing := range AllowedMeldingStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid MeldingStatus", value)
}

// NewMeldingStatusFromValue returns a pointer to a valid MeldingStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewMeldingStatusFromValue(v int32) (*MeldingStatus, error) {
	ev := MeldingStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for MeldingStatus: valid values are %v", v, AllowedMeldingStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v MeldingStatus) IsValid() bool {
	for _, existing := range AllowedMeldingStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to MeldingStatus value
func (v MeldingStatus) Ptr() *MeldingStatus {
	return &v
}

type NullableMeldingStatus struct {
	value *MeldingStatus
	isSet bool
}

func (v NullableMeldingStatus) Get() *MeldingStatus {
	return v.value
}

func (v *NullableMeldingStatus) Set(val *MeldingStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableMeldingStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableMeldingStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeldingStatus(val *MeldingStatus) *NullableMeldingStatus {
	return &NullableMeldingStatus{value: val, isSet: true}
}

func (v NullableMeldingStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeldingStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

