/*
AMSVR Broker API

# Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##        

API version: release-0.6.14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package broker

import (
	"encoding/json"
)

// NieuweAfsluitingZaakGoedkeurenRequest struct for NieuweAfsluitingZaakGoedkeurenRequest
type NieuweAfsluitingZaakGoedkeurenRequest struct {
	Description string `json:"description"`
	Gebruiksfunctie GebruiksfunctieEnum `json:"gebruiksfunctie"`
}

// NewNieuweAfsluitingZaakGoedkeurenRequest instantiates a new NieuweAfsluitingZaakGoedkeurenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNieuweAfsluitingZaakGoedkeurenRequest(description string, gebruiksfunctie GebruiksfunctieEnum) *NieuweAfsluitingZaakGoedkeurenRequest {
	this := NieuweAfsluitingZaakGoedkeurenRequest{}
	this.Description = description
	this.Gebruiksfunctie = gebruiksfunctie
	return &this
}

// NewNieuweAfsluitingZaakGoedkeurenRequestWithDefaults instantiates a new NieuweAfsluitingZaakGoedkeurenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNieuweAfsluitingZaakGoedkeurenRequestWithDefaults() *NieuweAfsluitingZaakGoedkeurenRequest {
	this := NieuweAfsluitingZaakGoedkeurenRequest{}
	return &this
}

// GetDescription returns the Description field value
func (o *NieuweAfsluitingZaakGoedkeurenRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *NieuweAfsluitingZaakGoedkeurenRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *NieuweAfsluitingZaakGoedkeurenRequest) SetDescription(v string) {
	o.Description = v
}

// GetGebruiksfunctie returns the Gebruiksfunctie field value
func (o *NieuweAfsluitingZaakGoedkeurenRequest) GetGebruiksfunctie() GebruiksfunctieEnum {
	if o == nil {
		var ret GebruiksfunctieEnum
		return ret
	}

	return o.Gebruiksfunctie
}

// GetGebruiksfunctieOk returns a tuple with the Gebruiksfunctie field value
// and a boolean to check if the value has been set.
func (o *NieuweAfsluitingZaakGoedkeurenRequest) GetGebruiksfunctieOk() (*GebruiksfunctieEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gebruiksfunctie, true
}

// SetGebruiksfunctie sets field value
func (o *NieuweAfsluitingZaakGoedkeurenRequest) SetGebruiksfunctie(v GebruiksfunctieEnum) {
	o.Gebruiksfunctie = v
}

func (o NieuweAfsluitingZaakGoedkeurenRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["gebruiksfunctie"] = o.Gebruiksfunctie
	}
	return json.Marshal(toSerialize)
}

type NullableNieuweAfsluitingZaakGoedkeurenRequest struct {
	value *NieuweAfsluitingZaakGoedkeurenRequest
	isSet bool
}

func (v NullableNieuweAfsluitingZaakGoedkeurenRequest) Get() *NieuweAfsluitingZaakGoedkeurenRequest {
	return v.value
}

func (v *NullableNieuweAfsluitingZaakGoedkeurenRequest) Set(val *NieuweAfsluitingZaakGoedkeurenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNieuweAfsluitingZaakGoedkeurenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNieuweAfsluitingZaakGoedkeurenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNieuweAfsluitingZaakGoedkeurenRequest(val *NieuweAfsluitingZaakGoedkeurenRequest) *NullableNieuweAfsluitingZaakGoedkeurenRequest {
	return &NullableNieuweAfsluitingZaakGoedkeurenRequest{value: val, isSet: true}
}

func (v NullableNieuweAfsluitingZaakGoedkeurenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNieuweAfsluitingZaakGoedkeurenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


