/*
AMSVR Broker API

# Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##        

API version: release-0.6.14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package broker

import (
	"encoding/json"
	"time"
)

// AfspraakRequest struct for AfspraakRequest
type AfspraakRequest struct {
	StartTijd time.Time `json:"start_tijd"`
	EindTijd *time.Time `json:"eind_tijd,omitempty"`
	Titel string `json:"titel"`
	Aansluiting NullableInt32 `json:"aansluiting,omitempty"`
}

// NewAfspraakRequest instantiates a new AfspraakRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAfspraakRequest(startTijd time.Time, titel string) *AfspraakRequest {
	this := AfspraakRequest{}
	this.StartTijd = startTijd
	this.Titel = titel
	return &this
}

// NewAfspraakRequestWithDefaults instantiates a new AfspraakRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAfspraakRequestWithDefaults() *AfspraakRequest {
	this := AfspraakRequest{}
	return &this
}

// GetStartTijd returns the StartTijd field value
func (o *AfspraakRequest) GetStartTijd() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartTijd
}

// GetStartTijdOk returns a tuple with the StartTijd field value
// and a boolean to check if the value has been set.
func (o *AfspraakRequest) GetStartTijdOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTijd, true
}

// SetStartTijd sets field value
func (o *AfspraakRequest) SetStartTijd(v time.Time) {
	o.StartTijd = v
}

// GetEindTijd returns the EindTijd field value if set, zero value otherwise.
func (o *AfspraakRequest) GetEindTijd() time.Time {
	if o == nil || o.EindTijd == nil {
		var ret time.Time
		return ret
	}
	return *o.EindTijd
}

// GetEindTijdOk returns a tuple with the EindTijd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AfspraakRequest) GetEindTijdOk() (*time.Time, bool) {
	if o == nil || o.EindTijd == nil {
		return nil, false
	}
	return o.EindTijd, true
}

// HasEindTijd returns a boolean if a field has been set.
func (o *AfspraakRequest) HasEindTijd() bool {
	if o != nil && o.EindTijd != nil {
		return true
	}

	return false
}

// SetEindTijd gets a reference to the given time.Time and assigns it to the EindTijd field.
func (o *AfspraakRequest) SetEindTijd(v time.Time) {
	o.EindTijd = &v
}

// GetTitel returns the Titel field value
func (o *AfspraakRequest) GetTitel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Titel
}

// GetTitelOk returns a tuple with the Titel field value
// and a boolean to check if the value has been set.
func (o *AfspraakRequest) GetTitelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Titel, true
}

// SetTitel sets field value
func (o *AfspraakRequest) SetTitel(v string) {
	o.Titel = v
}

// GetAansluiting returns the Aansluiting field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AfspraakRequest) GetAansluiting() int32 {
	if o == nil || o.Aansluiting.Get() == nil {
		var ret int32
		return ret
	}
	return *o.Aansluiting.Get()
}

// GetAansluitingOk returns a tuple with the Aansluiting field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AfspraakRequest) GetAansluitingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Aansluiting.Get(), o.Aansluiting.IsSet()
}

// HasAansluiting returns a boolean if a field has been set.
func (o *AfspraakRequest) HasAansluiting() bool {
	if o != nil && o.Aansluiting.IsSet() {
		return true
	}

	return false
}

// SetAansluiting gets a reference to the given NullableInt32 and assigns it to the Aansluiting field.
func (o *AfspraakRequest) SetAansluiting(v int32) {
	o.Aansluiting.Set(&v)
}
// SetAansluitingNil sets the value for Aansluiting to be an explicit nil
func (o *AfspraakRequest) SetAansluitingNil() {
	o.Aansluiting.Set(nil)
}

// UnsetAansluiting ensures that no value is present for Aansluiting, not even an explicit nil
func (o *AfspraakRequest) UnsetAansluiting() {
	o.Aansluiting.Unset()
}

func (o AfspraakRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["start_tijd"] = o.StartTijd
	}
	if o.EindTijd != nil {
		toSerialize["eind_tijd"] = o.EindTijd
	}
	if true {
		toSerialize["titel"] = o.Titel
	}
	if o.Aansluiting.IsSet() {
		toSerialize["aansluiting"] = o.Aansluiting.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableAfspraakRequest struct {
	value *AfspraakRequest
	isSet bool
}

func (v NullableAfspraakRequest) Get() *AfspraakRequest {
	return v.value
}

func (v *NullableAfspraakRequest) Set(val *AfspraakRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAfspraakRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAfspraakRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAfspraakRequest(val *AfspraakRequest) *NullableAfspraakRequest {
	return &NullableAfspraakRequest{value: val, isSet: true}
}

func (v NullableAfspraakRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAfspraakRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


