/*
AMSVR Broker API

# Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##        

API version: release-0.6.14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package broker

import (
	"encoding/json"
	"time"
)

// AanwezigCriterium struct for AanwezigCriterium
type AanwezigCriterium struct {
	Id int32 `json:"id"`
	Sector int32 `json:"sector"`
	Criterium int32 `json:"criterium"`
	LaatstGemeld NullableTime `json:"laatst_gemeld"`
	LaatsteToestand NullableMeldingToestand `json:"laatste_toestand"`
	LaatsteStatus NullableMeldingStatus `json:"laatste_status"`
}

// NewAanwezigCriterium instantiates a new AanwezigCriterium object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAanwezigCriterium(id int32, sector int32, criterium int32, laatstGemeld NullableTime, laatsteToestand NullableMeldingToestand, laatsteStatus NullableMeldingStatus) *AanwezigCriterium {
	this := AanwezigCriterium{}
	this.Id = id
	this.Sector = sector
	this.Criterium = criterium
	this.LaatstGemeld = laatstGemeld
	this.LaatsteToestand = laatsteToestand
	this.LaatsteStatus = laatsteStatus
	return &this
}

// NewAanwezigCriteriumWithDefaults instantiates a new AanwezigCriterium object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAanwezigCriteriumWithDefaults() *AanwezigCriterium {
	this := AanwezigCriterium{}
	return &this
}

// GetId returns the Id field value
func (o *AanwezigCriterium) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AanwezigCriterium) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AanwezigCriterium) SetId(v int32) {
	o.Id = v
}

// GetSector returns the Sector field value
func (o *AanwezigCriterium) GetSector() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Sector
}

// GetSectorOk returns a tuple with the Sector field value
// and a boolean to check if the value has been set.
func (o *AanwezigCriterium) GetSectorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sector, true
}

// SetSector sets field value
func (o *AanwezigCriterium) SetSector(v int32) {
	o.Sector = v
}

// GetCriterium returns the Criterium field value
func (o *AanwezigCriterium) GetCriterium() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Criterium
}

// GetCriteriumOk returns a tuple with the Criterium field value
// and a boolean to check if the value has been set.
func (o *AanwezigCriterium) GetCriteriumOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Criterium, true
}

// SetCriterium sets field value
func (o *AanwezigCriterium) SetCriterium(v int32) {
	o.Criterium = v
}

// GetLaatstGemeld returns the LaatstGemeld field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *AanwezigCriterium) GetLaatstGemeld() time.Time {
	if o == nil || o.LaatstGemeld.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LaatstGemeld.Get()
}

// GetLaatstGemeldOk returns a tuple with the LaatstGemeld field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AanwezigCriterium) GetLaatstGemeldOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LaatstGemeld.Get(), o.LaatstGemeld.IsSet()
}

// SetLaatstGemeld sets field value
func (o *AanwezigCriterium) SetLaatstGemeld(v time.Time) {
	o.LaatstGemeld.Set(&v)
}

// GetLaatsteToestand returns the LaatsteToestand field value
// If the value is explicit nil, the zero value for MeldingToestand will be returned
func (o *AanwezigCriterium) GetLaatsteToestand() MeldingToestand {
	if o == nil || o.LaatsteToestand.Get() == nil {
		var ret MeldingToestand
		return ret
	}

	return *o.LaatsteToestand.Get()
}

// GetLaatsteToestandOk returns a tuple with the LaatsteToestand field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AanwezigCriterium) GetLaatsteToestandOk() (*MeldingToestand, bool) {
	if o == nil {
		return nil, false
	}
	return o.LaatsteToestand.Get(), o.LaatsteToestand.IsSet()
}

// SetLaatsteToestand sets field value
func (o *AanwezigCriterium) SetLaatsteToestand(v MeldingToestand) {
	o.LaatsteToestand.Set(&v)
}

// GetLaatsteStatus returns the LaatsteStatus field value
// If the value is explicit nil, the zero value for MeldingStatus will be returned
func (o *AanwezigCriterium) GetLaatsteStatus() MeldingStatus {
	if o == nil || o.LaatsteStatus.Get() == nil {
		var ret MeldingStatus
		return ret
	}

	return *o.LaatsteStatus.Get()
}

// GetLaatsteStatusOk returns a tuple with the LaatsteStatus field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AanwezigCriterium) GetLaatsteStatusOk() (*MeldingStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.LaatsteStatus.Get(), o.LaatsteStatus.IsSet()
}

// SetLaatsteStatus sets field value
func (o *AanwezigCriterium) SetLaatsteStatus(v MeldingStatus) {
	o.LaatsteStatus.Set(&v)
}

func (o AanwezigCriterium) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["sector"] = o.Sector
	}
	if true {
		toSerialize["criterium"] = o.Criterium
	}
	if true {
		toSerialize["laatst_gemeld"] = o.LaatstGemeld.Get()
	}
	if true {
		toSerialize["laatste_toestand"] = o.LaatsteToestand.Get()
	}
	if true {
		toSerialize["laatste_status"] = o.LaatsteStatus.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableAanwezigCriterium struct {
	value *AanwezigCriterium
	isSet bool
}

func (v NullableAanwezigCriterium) Get() *AanwezigCriterium {
	return v.value
}

func (v *NullableAanwezigCriterium) Set(val *AanwezigCriterium) {
	v.value = val
	v.isSet = true
}

func (v NullableAanwezigCriterium) IsSet() bool {
	return v.isSet
}

func (v *NullableAanwezigCriterium) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAanwezigCriterium(val *AanwezigCriterium) *NullableAanwezigCriterium {
	return &NullableAanwezigCriterium{value: val, isSet: true}
}

func (v NullableAanwezigCriterium) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAanwezigCriterium) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


