/*
AMSVR Broker API

# Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##        

API version: release-0.6.14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package broker

import (
	"encoding/json"
)

// AfsluitingZaakGoedkeurenRequest struct for AfsluitingZaakGoedkeurenRequest
type AfsluitingZaakGoedkeurenRequest struct {
	Description string `json:"description"`
	// Wanneer wordt de aansluiting definitief verwijderd?
	DefinitieveDatum NullableString `json:"definitieve_datum,omitempty"`
}

// NewAfsluitingZaakGoedkeurenRequest instantiates a new AfsluitingZaakGoedkeurenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAfsluitingZaakGoedkeurenRequest(description string) *AfsluitingZaakGoedkeurenRequest {
	this := AfsluitingZaakGoedkeurenRequest{}
	this.Description = description
	return &this
}

// NewAfsluitingZaakGoedkeurenRequestWithDefaults instantiates a new AfsluitingZaakGoedkeurenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAfsluitingZaakGoedkeurenRequestWithDefaults() *AfsluitingZaakGoedkeurenRequest {
	this := AfsluitingZaakGoedkeurenRequest{}
	return &this
}

// GetDescription returns the Description field value
func (o *AfsluitingZaakGoedkeurenRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *AfsluitingZaakGoedkeurenRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *AfsluitingZaakGoedkeurenRequest) SetDescription(v string) {
	o.Description = v
}

// GetDefinitieveDatum returns the DefinitieveDatum field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AfsluitingZaakGoedkeurenRequest) GetDefinitieveDatum() string {
	if o == nil || o.DefinitieveDatum.Get() == nil {
		var ret string
		return ret
	}
	return *o.DefinitieveDatum.Get()
}

// GetDefinitieveDatumOk returns a tuple with the DefinitieveDatum field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AfsluitingZaakGoedkeurenRequest) GetDefinitieveDatumOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefinitieveDatum.Get(), o.DefinitieveDatum.IsSet()
}

// HasDefinitieveDatum returns a boolean if a field has been set.
func (o *AfsluitingZaakGoedkeurenRequest) HasDefinitieveDatum() bool {
	if o != nil && o.DefinitieveDatum.IsSet() {
		return true
	}

	return false
}

// SetDefinitieveDatum gets a reference to the given NullableString and assigns it to the DefinitieveDatum field.
func (o *AfsluitingZaakGoedkeurenRequest) SetDefinitieveDatum(v string) {
	o.DefinitieveDatum.Set(&v)
}
// SetDefinitieveDatumNil sets the value for DefinitieveDatum to be an explicit nil
func (o *AfsluitingZaakGoedkeurenRequest) SetDefinitieveDatumNil() {
	o.DefinitieveDatum.Set(nil)
}

// UnsetDefinitieveDatum ensures that no value is present for DefinitieveDatum, not even an explicit nil
func (o *AfsluitingZaakGoedkeurenRequest) UnsetDefinitieveDatum() {
	o.DefinitieveDatum.Unset()
}

func (o AfsluitingZaakGoedkeurenRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["description"] = o.Description
	}
	if o.DefinitieveDatum.IsSet() {
		toSerialize["definitieve_datum"] = o.DefinitieveDatum.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableAfsluitingZaakGoedkeurenRequest struct {
	value *AfsluitingZaakGoedkeurenRequest
	isSet bool
}

func (v NullableAfsluitingZaakGoedkeurenRequest) Get() *AfsluitingZaakGoedkeurenRequest {
	return v.value
}

func (v *NullableAfsluitingZaakGoedkeurenRequest) Set(val *AfsluitingZaakGoedkeurenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAfsluitingZaakGoedkeurenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAfsluitingZaakGoedkeurenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAfsluitingZaakGoedkeurenRequest(val *AfsluitingZaakGoedkeurenRequest) *NullableAfsluitingZaakGoedkeurenRequest {
	return &NullableAfsluitingZaakGoedkeurenRequest{value: val, isSet: true}
}

func (v NullableAfsluitingZaakGoedkeurenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAfsluitingZaakGoedkeurenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


