/*
AMSVR Broker API

# Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##        

API version: release-0.6.14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package broker

import (
	"encoding/json"
	"time"
)

// Melding struct for Melding
type Melding struct {
	Id int32 `json:"id"`
	// The naam field of the Criterium
	Criterium int32 `json:"criterium"`
	Tijd time.Time `json:"tijd"`
	Aansluitnummer string `json:"aansluitnummer"`
	// Reference to the number of the sector
	Sector NullableInt32 `json:"sector,omitempty"`
	// 0 = Rust, 1 = Alarm
	Status NullableMeldingStatus `json:"status,omitempty"`
	// 0 = Actief, 1 = Test, 2 = Passief
	Toestand NullableMeldingToestand `json:"toestand"`
	Data *string `json:"data,omitempty"`
	Actueel *bool `json:"actueel,omitempty"`
	GmsId NullableString `json:"gms_id,omitempty"`
	Oorzaak NullableString `json:"oorzaak,omitempty"`
	MeldingId NullableString `json:"melding_id,omitempty"`
	Prio NullablePrioEnum `json:"prio,omitempty"`
}

// NewMelding instantiates a new Melding object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMelding(id int32, criterium int32, tijd time.Time, aansluitnummer string, toestand NullableMeldingToestand) *Melding {
	this := Melding{}
	this.Id = id
	this.Criterium = criterium
	this.Tijd = tijd
	this.Aansluitnummer = aansluitnummer
	this.Toestand = toestand
	return &this
}

// NewMeldingWithDefaults instantiates a new Melding object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeldingWithDefaults() *Melding {
	this := Melding{}
	return &this
}

// GetId returns the Id field value
func (o *Melding) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Melding) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Melding) SetId(v int32) {
	o.Id = v
}

// GetCriterium returns the Criterium field value
func (o *Melding) GetCriterium() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Criterium
}

// GetCriteriumOk returns a tuple with the Criterium field value
// and a boolean to check if the value has been set.
func (o *Melding) GetCriteriumOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Criterium, true
}

// SetCriterium sets field value
func (o *Melding) SetCriterium(v int32) {
	o.Criterium = v
}

// GetTijd returns the Tijd field value
func (o *Melding) GetTijd() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Tijd
}

// GetTijdOk returns a tuple with the Tijd field value
// and a boolean to check if the value has been set.
func (o *Melding) GetTijdOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tijd, true
}

// SetTijd sets field value
func (o *Melding) SetTijd(v time.Time) {
	o.Tijd = v
}

// GetAansluitnummer returns the Aansluitnummer field value
func (o *Melding) GetAansluitnummer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Aansluitnummer
}

// GetAansluitnummerOk returns a tuple with the Aansluitnummer field value
// and a boolean to check if the value has been set.
func (o *Melding) GetAansluitnummerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Aansluitnummer, true
}

// SetAansluitnummer sets field value
func (o *Melding) SetAansluitnummer(v string) {
	o.Aansluitnummer = v
}

// GetSector returns the Sector field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Melding) GetSector() int32 {
	if o == nil || o.Sector.Get() == nil {
		var ret int32
		return ret
	}
	return *o.Sector.Get()
}

// GetSectorOk returns a tuple with the Sector field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Melding) GetSectorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sector.Get(), o.Sector.IsSet()
}

// HasSector returns a boolean if a field has been set.
func (o *Melding) HasSector() bool {
	if o != nil && o.Sector.IsSet() {
		return true
	}

	return false
}

// SetSector gets a reference to the given NullableInt32 and assigns it to the Sector field.
func (o *Melding) SetSector(v int32) {
	o.Sector.Set(&v)
}
// SetSectorNil sets the value for Sector to be an explicit nil
func (o *Melding) SetSectorNil() {
	o.Sector.Set(nil)
}

// UnsetSector ensures that no value is present for Sector, not even an explicit nil
func (o *Melding) UnsetSector() {
	o.Sector.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Melding) GetStatus() MeldingStatus {
	if o == nil || o.Status.Get() == nil {
		var ret MeldingStatus
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Melding) GetStatusOk() (*MeldingStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *Melding) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableMeldingStatus and assigns it to the Status field.
func (o *Melding) SetStatus(v MeldingStatus) {
	o.Status.Set(&v)
}
// SetStatusNil sets the value for Status to be an explicit nil
func (o *Melding) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *Melding) UnsetStatus() {
	o.Status.Unset()
}

// GetToestand returns the Toestand field value
// If the value is explicit nil, the zero value for MeldingToestand will be returned
func (o *Melding) GetToestand() MeldingToestand {
	if o == nil || o.Toestand.Get() == nil {
		var ret MeldingToestand
		return ret
	}

	return *o.Toestand.Get()
}

// GetToestandOk returns a tuple with the Toestand field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Melding) GetToestandOk() (*MeldingToestand, bool) {
	if o == nil {
		return nil, false
	}
	return o.Toestand.Get(), o.Toestand.IsSet()
}

// SetToestand sets field value
func (o *Melding) SetToestand(v MeldingToestand) {
	o.Toestand.Set(&v)
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *Melding) GetData() string {
	if o == nil || o.Data == nil {
		var ret string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Melding) GetDataOk() (*string, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *Melding) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given string and assigns it to the Data field.
func (o *Melding) SetData(v string) {
	o.Data = &v
}

// GetActueel returns the Actueel field value if set, zero value otherwise.
func (o *Melding) GetActueel() bool {
	if o == nil || o.Actueel == nil {
		var ret bool
		return ret
	}
	return *o.Actueel
}

// GetActueelOk returns a tuple with the Actueel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Melding) GetActueelOk() (*bool, bool) {
	if o == nil || o.Actueel == nil {
		return nil, false
	}
	return o.Actueel, true
}

// HasActueel returns a boolean if a field has been set.
func (o *Melding) HasActueel() bool {
	if o != nil && o.Actueel != nil {
		return true
	}

	return false
}

// SetActueel gets a reference to the given bool and assigns it to the Actueel field.
func (o *Melding) SetActueel(v bool) {
	o.Actueel = &v
}

// GetGmsId returns the GmsId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Melding) GetGmsId() string {
	if o == nil || o.GmsId.Get() == nil {
		var ret string
		return ret
	}
	return *o.GmsId.Get()
}

// GetGmsIdOk returns a tuple with the GmsId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Melding) GetGmsIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GmsId.Get(), o.GmsId.IsSet()
}

// HasGmsId returns a boolean if a field has been set.
func (o *Melding) HasGmsId() bool {
	if o != nil && o.GmsId.IsSet() {
		return true
	}

	return false
}

// SetGmsId gets a reference to the given NullableString and assigns it to the GmsId field.
func (o *Melding) SetGmsId(v string) {
	o.GmsId.Set(&v)
}
// SetGmsIdNil sets the value for GmsId to be an explicit nil
func (o *Melding) SetGmsIdNil() {
	o.GmsId.Set(nil)
}

// UnsetGmsId ensures that no value is present for GmsId, not even an explicit nil
func (o *Melding) UnsetGmsId() {
	o.GmsId.Unset()
}

// GetOorzaak returns the Oorzaak field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Melding) GetOorzaak() string {
	if o == nil || o.Oorzaak.Get() == nil {
		var ret string
		return ret
	}
	return *o.Oorzaak.Get()
}

// GetOorzaakOk returns a tuple with the Oorzaak field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Melding) GetOorzaakOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Oorzaak.Get(), o.Oorzaak.IsSet()
}

// HasOorzaak returns a boolean if a field has been set.
func (o *Melding) HasOorzaak() bool {
	if o != nil && o.Oorzaak.IsSet() {
		return true
	}

	return false
}

// SetOorzaak gets a reference to the given NullableString and assigns it to the Oorzaak field.
func (o *Melding) SetOorzaak(v string) {
	o.Oorzaak.Set(&v)
}
// SetOorzaakNil sets the value for Oorzaak to be an explicit nil
func (o *Melding) SetOorzaakNil() {
	o.Oorzaak.Set(nil)
}

// UnsetOorzaak ensures that no value is present for Oorzaak, not even an explicit nil
func (o *Melding) UnsetOorzaak() {
	o.Oorzaak.Unset()
}

// GetMeldingId returns the MeldingId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Melding) GetMeldingId() string {
	if o == nil || o.MeldingId.Get() == nil {
		var ret string
		return ret
	}
	return *o.MeldingId.Get()
}

// GetMeldingIdOk returns a tuple with the MeldingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Melding) GetMeldingIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MeldingId.Get(), o.MeldingId.IsSet()
}

// HasMeldingId returns a boolean if a field has been set.
func (o *Melding) HasMeldingId() bool {
	if o != nil && o.MeldingId.IsSet() {
		return true
	}

	return false
}

// SetMeldingId gets a reference to the given NullableString and assigns it to the MeldingId field.
func (o *Melding) SetMeldingId(v string) {
	o.MeldingId.Set(&v)
}
// SetMeldingIdNil sets the value for MeldingId to be an explicit nil
func (o *Melding) SetMeldingIdNil() {
	o.MeldingId.Set(nil)
}

// UnsetMeldingId ensures that no value is present for MeldingId, not even an explicit nil
func (o *Melding) UnsetMeldingId() {
	o.MeldingId.Unset()
}

// GetPrio returns the Prio field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Melding) GetPrio() PrioEnum {
	if o == nil || o.Prio.Get() == nil {
		var ret PrioEnum
		return ret
	}
	return *o.Prio.Get()
}

// GetPrioOk returns a tuple with the Prio field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Melding) GetPrioOk() (*PrioEnum, bool) {
	if o == nil {
		return nil, false
	}
	return o.Prio.Get(), o.Prio.IsSet()
}

// HasPrio returns a boolean if a field has been set.
func (o *Melding) HasPrio() bool {
	if o != nil && o.Prio.IsSet() {
		return true
	}

	return false
}

// SetPrio gets a reference to the given NullablePrioEnum and assigns it to the Prio field.
func (o *Melding) SetPrio(v PrioEnum) {
	o.Prio.Set(&v)
}
// SetPrioNil sets the value for Prio to be an explicit nil
func (o *Melding) SetPrioNil() {
	o.Prio.Set(nil)
}

// UnsetPrio ensures that no value is present for Prio, not even an explicit nil
func (o *Melding) UnsetPrio() {
	o.Prio.Unset()
}

func (o Melding) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["criterium"] = o.Criterium
	}
	if true {
		toSerialize["tijd"] = o.Tijd
	}
	if true {
		toSerialize["aansluitnummer"] = o.Aansluitnummer
	}
	if o.Sector.IsSet() {
		toSerialize["sector"] = o.Sector.Get()
	}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	if true {
		toSerialize["toestand"] = o.Toestand.Get()
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Actueel != nil {
		toSerialize["actueel"] = o.Actueel
	}
	if o.GmsId.IsSet() {
		toSerialize["gms_id"] = o.GmsId.Get()
	}
	if o.Oorzaak.IsSet() {
		toSerialize["oorzaak"] = o.Oorzaak.Get()
	}
	if o.MeldingId.IsSet() {
		toSerialize["melding_id"] = o.MeldingId.Get()
	}
	if o.Prio.IsSet() {
		toSerialize["prio"] = o.Prio.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableMelding struct {
	value *Melding
	isSet bool
}

func (v NullableMelding) Get() *Melding {
	return v.value
}

func (v *NullableMelding) Set(val *Melding) {
	v.value = val
	v.isSet = true
}

func (v NullableMelding) IsSet() bool {
	return v.isSet
}

func (v *NullableMelding) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMelding(val *Melding) *NullableMelding {
	return &NullableMelding{value: val, isSet: true}
}

func (v NullableMelding) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMelding) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


