/*
 * AMSVR Broker API
 *
 * # Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##        
 *
 * API version: release-0.6.0.24
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package broker
// MigratieZaakStatusEnum the model 'MigratieZaakStatusEnum'
type MigratieZaakStatusEnum string

// List of MigratieZaakStatusEnum
const (
	MIGRATIEZAAKSTATUSENUM_NIEUW MigratieZaakStatusEnum = "nieuw"
	MIGRATIEZAAKSTATUSENUM_INGEDIEND MigratieZaakStatusEnum = "ingediend"
	MIGRATIEZAAKSTATUSENUM_INGEPLAND MigratieZaakStatusEnum = "ingepland"
	MIGRATIEZAAKSTATUSENUM_GMS_DOORGEVOERD MigratieZaakStatusEnum = "gms_doorgevoerd"
	MIGRATIEZAAKSTATUSENUM_GOEDGEKEURD MigratieZaakStatusEnum = "goedgekeurd"
	MIGRATIEZAAKSTATUSENUM_GEANNULEERD MigratieZaakStatusEnum = "geannuleerd"
	MIGRATIEZAAKSTATUSENUM_GMS_VERWIJDERD MigratieZaakStatusEnum = "gms_verwijderd"
)
