/*
 * AMSVR Broker API
 *
 * # Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##        
 *
 * API version: release-0.6.0.24
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package broker
import (
	"time"
)
// MeldingRequest struct for MeldingRequest
type MeldingRequest struct {
	// The naam field of the Criterium
	Criterium int32 `json:"criterium"`
	Tijd time.Time `json:"tijd"`
	// Reference to the number of the sector
	Sector *int32 `json:"sector,omitempty"`
	// 0 = Rust, 1 = Alarm
	Status MeldingStatus `json:"status,omitempty"`
	// 0 = Actief, 1 = test, 2 = Passief
	Toestand MeldingToestand `json:"toestand"`
	Data string `json:"data,omitempty"`
	Actueel bool `json:"actueel,omitempty"`
	GmsId *string `json:"gms_id,omitempty"`
	Oorzaak *string `json:"oorzaak,omitempty"`
	FepNr int32 `json:"fep_nr"`
	VolgNr int32 `json:"volg_nr"`
	MeldingId *string `json:"melding_id,omitempty"`
	Prio PrioEnum `json:"prio,omitempty"`
}
