/*
AMSVR Broker API

# Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##        

API version: release-0.6.14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package broker

import (
	"encoding/json"
)

// AfsluitingZaakBevestigenRequest struct for AfsluitingZaakBevestigenRequest
type AfsluitingZaakBevestigenRequest struct {
	Description string `json:"description"`
}

// NewAfsluitingZaakBevestigenRequest instantiates a new AfsluitingZaakBevestigenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAfsluitingZaakBevestigenRequest(description string) *AfsluitingZaakBevestigenRequest {
	this := AfsluitingZaakBevestigenRequest{}
	this.Description = description
	return &this
}

// NewAfsluitingZaakBevestigenRequestWithDefaults instantiates a new AfsluitingZaakBevestigenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAfsluitingZaakBevestigenRequestWithDefaults() *AfsluitingZaakBevestigenRequest {
	this := AfsluitingZaakBevestigenRequest{}
	return &this
}

// GetDescription returns the Description field value
func (o *AfsluitingZaakBevestigenRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *AfsluitingZaakBevestigenRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *AfsluitingZaakBevestigenRequest) SetDescription(v string) {
	o.Description = v
}

func (o AfsluitingZaakBevestigenRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableAfsluitingZaakBevestigenRequest struct {
	value *AfsluitingZaakBevestigenRequest
	isSet bool
}

func (v NullableAfsluitingZaakBevestigenRequest) Get() *AfsluitingZaakBevestigenRequest {
	return v.value
}

func (v *NullableAfsluitingZaakBevestigenRequest) Set(val *AfsluitingZaakBevestigenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAfsluitingZaakBevestigenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAfsluitingZaakBevestigenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAfsluitingZaakBevestigenRequest(val *AfsluitingZaakBevestigenRequest) *NullableAfsluitingZaakBevestigenRequest {
	return &NullableAfsluitingZaakBevestigenRequest{value: val, isSet: true}
}

func (v NullableAfsluitingZaakBevestigenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAfsluitingZaakBevestigenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


