/*
 * AMSVR Broker API
 *
 * # Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##        
 *
 * API version: release-0.6.0.24
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package broker
// BronEnum the model 'BronEnum'
type BronEnum string

// List of BronEnum
const (
	BRONENUM_IMPORT BronEnum = "import"
	BRONENUM_NIEUW BronEnum = "nieuw"
	BRONENUM_MIGRATIE BronEnum = "migratie"
	BRONENUM_API BronEnum = "api"
)
