/*
AMSVR Broker API

# Introductie     Voor u heeft u de online documentatie van de AMSVR Broker API. Omdat het een Nederlands domein      betreft worden er Engelse en Nederlandse terminologie door elkaar heen gebruikt.  Liefhebbers van de Swagger UI kunnen [hier terecht](/swagger-ui). Daarnaast is de API eveneens beschikbaar in de op endpoint niveau zoals bijvoorbeeld [hier](/api/aansluitingen).  ##        

API version: release-0.6.14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package broker

import (
	"encoding/json"
	"time"
)

// MutatieZaakAangepastInDeBrokerRequest struct for MutatieZaakAangepastInDeBrokerRequest
type MutatieZaakAangepastInDeBrokerRequest struct {
	Description *string `json:"description,omitempty"`
	AfspraakTijd *time.Time `json:"afspraak_tijd,omitempty"`
}

// NewMutatieZaakAangepastInDeBrokerRequest instantiates a new MutatieZaakAangepastInDeBrokerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMutatieZaakAangepastInDeBrokerRequest() *MutatieZaakAangepastInDeBrokerRequest {
	this := MutatieZaakAangepastInDeBrokerRequest{}
	return &this
}

// NewMutatieZaakAangepastInDeBrokerRequestWithDefaults instantiates a new MutatieZaakAangepastInDeBrokerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMutatieZaakAangepastInDeBrokerRequestWithDefaults() *MutatieZaakAangepastInDeBrokerRequest {
	this := MutatieZaakAangepastInDeBrokerRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MutatieZaakAangepastInDeBrokerRequest) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MutatieZaakAangepastInDeBrokerRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MutatieZaakAangepastInDeBrokerRequest) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MutatieZaakAangepastInDeBrokerRequest) SetDescription(v string) {
	o.Description = &v
}

// GetAfspraakTijd returns the AfspraakTijd field value if set, zero value otherwise.
func (o *MutatieZaakAangepastInDeBrokerRequest) GetAfspraakTijd() time.Time {
	if o == nil || o.AfspraakTijd == nil {
		var ret time.Time
		return ret
	}
	return *o.AfspraakTijd
}

// GetAfspraakTijdOk returns a tuple with the AfspraakTijd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MutatieZaakAangepastInDeBrokerRequest) GetAfspraakTijdOk() (*time.Time, bool) {
	if o == nil || o.AfspraakTijd == nil {
		return nil, false
	}
	return o.AfspraakTijd, true
}

// HasAfspraakTijd returns a boolean if a field has been set.
func (o *MutatieZaakAangepastInDeBrokerRequest) HasAfspraakTijd() bool {
	if o != nil && o.AfspraakTijd != nil {
		return true
	}

	return false
}

// SetAfspraakTijd gets a reference to the given time.Time and assigns it to the AfspraakTijd field.
func (o *MutatieZaakAangepastInDeBrokerRequest) SetAfspraakTijd(v time.Time) {
	o.AfspraakTijd = &v
}

func (o MutatieZaakAangepastInDeBrokerRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.AfspraakTijd != nil {
		toSerialize["afspraak_tijd"] = o.AfspraakTijd
	}
	return json.Marshal(toSerialize)
}

type NullableMutatieZaakAangepastInDeBrokerRequest struct {
	value *MutatieZaakAangepastInDeBrokerRequest
	isSet bool
}

func (v NullableMutatieZaakAangepastInDeBrokerRequest) Get() *MutatieZaakAangepastInDeBrokerRequest {
	return v.value
}

func (v *NullableMutatieZaakAangepastInDeBrokerRequest) Set(val *MutatieZaakAangepastInDeBrokerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMutatieZaakAangepastInDeBrokerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMutatieZaakAangepastInDeBrokerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMutatieZaakAangepastInDeBrokerRequest(val *MutatieZaakAangepastInDeBrokerRequest) *NullableMutatieZaakAangepastInDeBrokerRequest {
	return &NullableMutatieZaakAangepastInDeBrokerRequest{value: val, isSet: true}
}

func (v NullableMutatieZaakAangepastInDeBrokerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMutatieZaakAangepastInDeBrokerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


